id: "obj-d8f178b0-3315-4690-ae4b-0a16a6ada65d"
name: "api-server"
slug: "api-server"
category: "busticket"
subcategory: "backend"
description: "api-server project"
status: "active"
author: "Claude"
created_at: "2025-12-29T19:17:03+01:00"
updated_at: "2025-12-29T19:17:03+01:00"
tags:
  - "busticket"
  - "backend"
  - "example"
default_folders:
  - "plany"
  - "instrukce"
  - "code"
  - "docs"
