id: "obj-245cf08d-1e08-443d-aa58-7ad55e464ed4"
name: "bus-ticket"
slug: "bus-ticket"
category: "odoo"
subcategory: "mobil"
description: "bus-ticket project"
status: "active"
author: "Claude"
created_at: "2025-12-29T19:17:03+01:00"
updated_at: "2025-12-29T19:17:03+01:00"
tags:
  - "odoo"
  - "mobil"
  - "example"
default_folders:
  - "plany"
  - "instrukce"
  - "code"
  - "docs"
