id: "obj-482a6d90-9a95-4148-b64e-02a7ef4ec0dc"
name: "web-app"
slug: "web-app"
category: "busticket"
subcategory: "frontend"
description: "web-app project"
status: "active"
author: "Claude"
created_at: "2025-12-29T19:17:03+01:00"
updated_at: "2025-12-29T19:17:03+01:00"
tags:
  - "busticket"
  - "frontend"
  - "example"
default_folders:
  - "plany"
  - "instrukce"
  - "code"
  - "docs"
