id: "subcat-busticket-backend"
name: "backend"
slug: "backend"
category: "busticket"
description: "backend subcategory"
is_active: true
created_at: "2025-12-29T19:17:03+01:00"
updated_at: "2025-12-29T19:17:03+01:00"
